version: "3"

networks:
  directus:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "azulapp"
      MYSQL_USER: "eder"
      MYSQL_PASSWORD: "eder"
      MYSQL_ROOT_PASSWORD: "eder"
    ports:
      - "33060:3306"
    networks:
      - directus

  directus:
    image: directus/directus:v8-apache
    ports:
      - "8081:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "secretive things"
      DIRECTUS_AUTH_SECRETKEY: "secret"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "azulapp"
      DIRECTUS_DATABASE_USERNAME: "eder"
      DIRECTUS_DATABASE_PASSWORD: "eder"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads    
    networks:
      - directus